### ISSUE TITLE
Consider using emails instead of URIs for identity

### ISSUE THREAD

**Issue by steveklabnik** [tent/tent.io#6]
One of the reasons that OpenID failed so hard was that they used URIs for identity; users are much, much more familiar with an email as an identifier.

WebFinger is one sample standard that may help here.

**Comment by bnb** [comment]
@michaelmd As far as I know, HTTPS is required as of 0.3 to solve this problem. To some degree, I know you can drop `https://` because of that. I've been involved in a lot of the discussion surrounding that, and I don't think the port has ever mattered.
